dc_assistant/dc_assistant/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from .views import MainView, APIRootView
from secret.views import UserLoginView, UserProfileView, UserChangePasswordView
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView
from dc_assistant.admin import admin_site

urlpatterns = [
    path('', MainView.as_view(), name='home'),
    path('admin/', admin_site.urls),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('change-password/', UserChangePasswordView.as_view(), name='change_password'),
    path('change-password/done/', PasswordChangeDoneView.as_view(template_name='secret/change_password_done.html'), name='change_password_done'),
    path('api/', APIRootView.as_view(), name='api-root'),
    path('api/secrets/', include('secret.api.urls')),
    path('api/organisation/', include('organisation.api.urls')),
    path('organisation/', include('organisation.urls')),
    path('extend/', include('extend.urls')),
    path('secret/', include('secret.urls')),
    ]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

dc_assistant/extend/urls.py
from django.urls import path, re_path

from extend import views
from .views import RackAutocomplete


app_name = 'extend'
urlpatterns = [

    path('tags/', views.TagListView.as_view(), name='tag_list'),
    path('rack-autocomplete', RackAutocomplete.as_view(), name='rack_autocomplete'),
    ]

dc_assistant/organisation/api/urls.py
from rest_framework import routers

from . import views


class OrganisationRootView(routers.APIRootView):
    """
    Organisation API root view
    """
    def get_view_name(self):
        return 'Organisation'

router = routers.DefaultRouter()
router.APIRootView = OrganisationRootView

router.register('devices', views.DeviceViewSet)

app_name = 'organisation-api'
urlpatterns = router.urls

dc_assistant/organisation/urls.py
from django.urls import path
from . import views
from secret.views import secret_add


app_name = 'organisation'

urlpatterns = [
    path('regions/', views.RegionListView.as_view(), name='region_list'),
    path('regions/add', views.RegionAdd.as_view(), name='region_add'),
    path('regions/<int:pk>/edit', views.RegionEdit.as_view(), name='region_edit'),

    path('locations/', views.LocationListView.as_view(), name='location_list'),
    path('locations/add', views.LocationAdd.as_view(), name='location_add'),
    path('locations/<slug:slug>/', views.LocationView.as_view(), name='location'),
    path('locations/<slug:slug>/edit', views.LocationEdit.as_view(), name='location_edit'),

    path('racks/', views.RackListView.as_view(), name='rack_list'),
    path('racks/add', views.RackAdd.as_view(), name='rack_add'),
    path('racks/<int:pk>/', views.RackView.as_view(), name='rack'),
    path('racks/<int:pk>/edit/', views.RackEdit.as_view(), name='rack_edit'),

    path('models/', views.VendorModelListView.as_view(), name='model_list'),
    path('models/add', views.VendorModelAdd.as_view(), name='model_add'),
    path('models/<int:pk>/edit/', views.VendorModelEdit.as_view(), name='model_edit'),

    path('roles/', views.RoleDeviceListView.as_view(), name='role_list'),
    path('roles/add', views.RoleDeviceAdd.as_view(), name='role_add'),
    path('roles/<int:pk>/edit/', views.RoleDeviceEdit.as_view(), name='role_edit'),

    path('platforms/', views.PlatformListView.as_view(), name='platform_list'),
    path('platforms/add', views.PlatformAdd.as_view(), name='platfrom_add'),
    path('platforms/<slug:slug>/edit/', views.PlatformEdit.as_view(), name='platform_edit'),

    path('vendors/', views.VendorListView.as_view(), name='vendor_list'),
    path('vendors/add', views.VendorAdd.as_view(), name='vendor_add'),
    path('vendors/<int:pk>/edit/', views.VendorEdit.as_view(), name='vendor_edit'),

    path('devices/', views.DeviceListView.as_view(), name='device_list'),
    path('devices/add', views.DeviceAdd.as_view(), name='device_add'),
    path('devices/<int:pk>/', views.DeviceView.as_view(), name='device'),
    path('devices/<int:pk>/edit/', views.DeviceEdit.as_view(), name='device_edit'),
    path('devices/<int:pk>/add-secret/', secret_add, name='device_addsecret'),

]

dc_assistant/organisation/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from mptt.models import MPTTModel, TreeForeignKey
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.core.validators import MaxValueValidator, MinValueValidator
from taggit.managers import TaggableManager
from extend.models import TaggedItem, ImgAttach, LoggingModel
from extend.forms import ColorField
from django.core.exceptions import ValidationError
from smart_selects.db_fields import ChainedForeignKey


class Region(MPTTModel):
    """
    Country/Regin/City where place location. Every instance of this class can be parent for the other one
    """
    parent = TreeForeignKey(
        to='self',
        on_delete=models.CASCADE,
        related_name='children',
        blank=True,
        null=True,
        db_index=True
    )
    name = models.CharField(
        max_length=50,
        unique=True
    )
    slug = models.SlugField(
        unique=True
    )
    class MPTTMeta:
        order_insertion_by = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return "{}?region={}".format(reverse('organisation:location_list'), self.slug)

class Location(LoggingModel):
    """
    The place where located IT infrastructure (Build, Office, DC and so on)
    """
    name = models.CharField(
        max_length=50,
        unique=True
    )
    slug = models.SlugField(
        unique=True
    )
    region = models.ForeignKey(
        to=Region,
        on_delete=models.SET_NULL,
        related_name='locations',
        blank=True,
        null=True
    )
    physical_address = models.CharField(
        max_length=200,
        blank=True
    )
    description = models.CharField(
        max_length=100,
        blank=True
    )
    comment = models.TextField(
        blank=True
    )
    tag = TaggableManager(
        through=TaggedItem
    )

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('organisation:location', args=[self.slug])

class Rack(LoggingModel):
    """
    Rack configuration
    """
    TYPE_1FRAME = '1-frame'
    TYPE_2FRAME = '2-frame'
    TYPE_WALLCABINET = 'wall-cabinet'
    TYPE_FLOORCABINET = 'floor-cabinet'

    TOP_TO_BUTTOM = 0
    BUTTOM_TO_TOP = 1


    RACK_TYPE_CHOICES = (
        (TYPE_1FRAME, 'One Frame rack'),
        (TYPE_2FRAME, 'Two Frame rack'),
        (TYPE_WALLCABINET, 'Wall-mounted cabinet'),
        (TYPE_FLOORCABINET, 'Floor-mounted cabinet'),
    )
    RACK_UNIT_DESC = (
        (TOP_TO_BUTTOM, 'Top to buttom'),
        (BUTTOM_TO_TOP, 'Buttom to top'),
    )
    name = models.CharField(
        max_length=50
    )
    location = models.ForeignKey(
        to=Location,
        on_delete=models.PROTECT,
        related_name='racks'
    )
    u_height = models.PositiveSmallIntegerField(
        default=44,
        verbose_name='Unit Height',
        validators=[MinValueValidator(1), MaxValueValidator(100)]
    )
    desc_units = models.BooleanField(
        choices=RACK_UNIT_DESC,
        default=BUTTOM_TO_TOP,
        verbose_name='Orientation',
        help_text='Default buttom to top'
    )
    racktype = models.CharField(
        max_length=50,
        choices=RACK_TYPE_CHOICES,
        default=TYPE_FLOORCABINET,
    )
    comment = models.TextField(
        blank=True
    )

    class Meta:
        ordering = ('location', 'name', 'pk')

    def __str__(self):
        return self.name

    # def __str__(self):
    #     return self.display_name or super().__str__()

    def get_absolute_url(self):
        return reverse('organisation:rack', args=[self.pk])

    # @property
    # def display_name(self):
    #     if self.location:
    #         return "{} ({})".format(self.name, self.location)
    #     elif self.name:
    #         return self.name
    #     return ""

class Vendor(LoggingModel):
    """
    Device`s vendors
    """
    name = models.CharField(
        max_length=50,
        unique=True
    )
    slug = models.SlugField(
        unique=True
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return "{}?vendor={}".format(reverse('organisation:model_list'), self.slug)

class VendorModel(LoggingModel):
    """
    Vendor models of device
    """
    vendor = models.ForeignKey(
        to=Vendor,
        on_delete=models.PROTECT,
        related_name='device_models'
    )
    model = models.CharField(
        max_length=50
    )
    slug = models.SlugField(
        unique=True
    )
    u_height = models.PositiveSmallIntegerField(
        default=1,
        verbose_name='Height (U)'
    )
    depth = models.BooleanField(
        default=True,
        verbose_name='Full Depth',
        help_text='Default is Full Depth'
    )
    front_image = models.ImageField(
        upload_to='imgs-devicemodel',
        blank=True
    )
    rear_image = models.ImageField(
        upload_to='imgs-devicemodel',
        blank=True
    )
    comment = models.TextField(
        blank=True
    )
    # def get_absolute_url(self):
    #     return reverse('organisation:vendormodel', args=[self.pk])
    @property
    def display_name(self):
        return '{} {}'.format(self.vendor.name, self.model)

    def __str__(self):
        return '{} {}'.format(self.vendor.name, self.model)


class Platform(LoggingModel):
    """
    Platform is software or firmware running on the devices
    """

    name = models.CharField(
        max_length=100,
        unique=True
    )
    slug = models.SlugField(
        unique=True,
        max_length=100
    )

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return "{}?platform={}".format(reverse('organisation:device_list'), self.slug)


class DeviceRole(LoggingModel):
    """
    Role of device or vm or service. For example device can be group by funcionality role (file server, mail server)
    """

    name = models.CharField(
        max_length=50,
        unique=True
    )
    slug = models.SlugField(
        unique=True
    )
    description = models.CharField(
        max_length=100,
        blank=True
    )
    color = ColorField()

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class Device(LoggingModel):
    """
    Device instance with. Each device must be assigned to location and can be place to rack.
    """

    #TODO: добавить обьединение в кластер, генерация IP адресов

    FRONT = 1
    REAR = 0

    RACK_SIDE_CHOICES = (
        (FRONT, 'Located at the front of rack'),
        (REAR, 'Located at the rear of rack'),
    )

    name = models.CharField(
        max_length=50,
        unique=True
    )
    device_model = models.ForeignKey(
        to=VendorModel,
        on_delete=models.PROTECT,
        related_name='instances'
    )
    device_role = models.ForeignKey(
        to=DeviceRole,
        on_delete=models.PROTECT,
        related_name='devices'
    )
    platform = models.ForeignKey(
        to=Platform,
        on_delete=models.SET_NULL,
        related_name='devices',
        blank=True,
        null=True
    )
    serial = models.CharField(
        max_length=50,
        blank=True,
        verbose_name='Serial number'
    )
    location = models.ForeignKey(
        to=Location,
        on_delete=models.PROTECT,
        related_name='devices'
    )
    rack = models.ForeignKey(
        to=Rack,
        on_delete=models.PROTECT,
        related_name='devices',
        blank=True,
        null=True
    )
    position = models.PositiveSmallIntegerField(
        blank=True,
        null=True,
        validators=[MinValueValidator(1)],
        verbose_name='Unit Number',
        help_text='Unit Number device starts location in the rack'
    )
    face_position = models.PositiveSmallIntegerField(
        choices=RACK_SIDE_CHOICES,
        default=FRONT,
        blank=True,
        null=True
    )
#    cluster = models.ForeignKey(
#        to='Cluster',
#        on_delete=models.SET_NULL,
#        related_name='devices',
#        blank=True,
#        null=True
#    )
#    primary_ip = models.OneToOneField(
#        to='IPAddress',
#        on_delete=models.SET_NULL,
#        related_name='primary_ip',
#        blank=True,
#        null=True,
#        verbose_name='Основной IP адрес'
#    )
    description = models.CharField(
        max_length=100,
        blank=True
    )
    comment = models.TextField(
        blank=True
    )
    images = GenericRelation(
        to=ImgAttach
    )
    tag = TaggableManager(
        through=TaggedItem
    )

    class Meta:
        ordering = ('name', 'pk')

    def __str__(self):
        return self.display_name or super().__str__()
        return self.name

    @property
    def display_name(self):
        if self.name:
            return self.name
        elif hasattr(self, 'device_model'):
            return "{}".format(self.device_model)
        return ""

    def get_absolute_url(self):
        return reverse('organisation:device', args=[self.pk])

    def clean(self):

        super().clean()

        if self.rack is None:
            if self.position:
                raise ValidationError({
                    'position': "Cannot select position without rack selected.",
                })
            if self.face_position:
                raise ValidationError({
                    'face_position': "Cannot select face_position without rack selected.",
                })

dc_assistant/organisation/api/views.py
from rest_framework.viewsets import ModelViewSet
from organisation.models import Device
from extend.filters import DeviceFilterSet
from .serializers import DeviceSerializer

class DeviceViewSet(ModelViewSet):
    queryset = Device.objects.prefetch_related(
        'device_model__vendor', 'device_role', 'platform', 'location', 'rack', 'tag',
    )
    filterset_class = DeviceFilterSet
    serializer_class = DeviceSerializer

dc_assistant/templates/organisation/device_tab.html
{% extends "base.html" %}
{% load static %}
{% load django_tables2 %}
{% load utils %}

{% block content %}
        <!-- ============================================================== -->
        <!-- Buttons-->
        <!-- ============================================================== -->
        <div class="container-fluid">
            <div class="row justify-content-end">
                <div class="col-md-9 col-sm-9">
                    <h2 class="card-title">Devices</h2>
                </div>
                <div class="col-md-3 col-sm-3 text-right">
                    <a class="btn btn-primary btn-lg" href="{% url 'organisation:device_add' %}" role="button">Add</a>
                </div>
            </div>
         </div>
         <hr>
        <!-- ============================================================== -->
        <!-- End Buttons-->
        <!-- ============================================================== -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                   <div class="table-responsive">
                       {% render_table table 'organisation/tmpl_table.html' %}
                   </div>
                </div>

            </div>
        </div>
{% endblock %}

dc_assistant/templates/organisation/platforms_tab.html
{% extends "base.html" %}
{% load static %}
{% load django_tables2 %}

{% block content %}
        <!-- ============================================================== -->
        <!-- Buttons-->
        <!-- ============================================================== -->
        <div class="container-fluid">
            <div class="row justify-content-end">
                <div class="col-md-9 col-sm-9">
                    <h2 class="card-title">Platforms</h2>
                </div>
                <div class="col-md-3 col-sm-3 text-right">
                    <a class="btn btn-primary btn-lg" href="{% url 'organisation:platfrom_add' %}" role="button">Add</a>
                </div>
            </div>
         </div>
         <hr>
        <!-- ============================================================== -->
        <!-- End Buttons-->
        <!-- ============================================================== -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="table-responsive">
                       {% render_table table 'organisation/tmpl_table.html' %}
                    </div>
                </div>

            </div>
        </div>
{% endblock %}

dc_assistant/templates/organisation/rack.html
{% extends "base.html" %}
{% load static %}
{% load utils %}

{% block content %}

        <!-- ============================================================== -->
        <!-- Buttons-->
        <!-- ============================================================== -->
         <div class="container-fluid">
            <div class="row ">
                <div class="col-md-9 col-sm-9">
                    <h2 class="card-title">{{ rack }}</h2>
                </div>
                <div class="col-md-3 col-sm-3 text-right">
<!--                    <a class="btn btn-warning btn-lg" href="{% url 'organisation:location_add' %}" role="button">Add</a>-->
                    <a class="btn btn-warning btn-lg" href="{% url 'organisation:rack_edit' rack.pk %}" role="button">Edit</a>
                </div>
            </div>
         </div>
         <hr>
        <!-- ============================================================== -->
        <!-- End Buttons-->
        <!-- ============================================================== -->
 <!-- Tabs -->
                        <div class="card">
                            <!-- Nav tabs -->
                            <ul class="nav nav-tabs" role="tablist">
                                <li class="nav-item"> <a class="nav-link active" data-toggle="tab" href="{{ rack.get_absolute_url }}" role="tab"><span class="hidden-sm-up"></span> <span class="hidden-xs-down">Rack</span></a> </li>
                                <li class="nav-item"> <a class="nav-link " data-toggle="tab" href="#" role="tab"><span class="hidden-sm-up"></span> <span class="hidden-xs-down">ChangeLogs</span></a> </li>
                            </ul>
                            <!-- Tab panes -->
                            <div class="tab-content tabcontent-border">
                                <div class="tab-pane active" id="home" role="tabpanel">
                                    <div class="p-20">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="card-body">
                                                    <h4 class="card-title m-b-0">Rack</h4>
                                                </div>
                                                <table class="table">
                                                    <tbody>
                                                        <tr>
                                                            <td>Location</td>
                                                            <td>
                                                                {% if rack.location.region %}
                                                                <a href="{{ rack.location.region.get_absolute_url }}"> {{ rack.location.region }} </a>
                                                                <i class="fas fa-angle-double-right"></i>
                                                                {% endif %}
                                                                <a href="{% url 'organisation:location' slug=rack.location.slug %}"> <span class="badge badge-secondary">{{ rack.location }} </span></a>
                                                            </td>
                                                        </tr>

                                                        <tr>
                                                            <td>Devices</td>
                                                            <td>
                                                                <a href="{% url 'organisation:device_list' %}?rack_id={{ rack.id }}">{{ rack.devices.count }}</a>
                                                            </td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </div>


                                            <div class="col-md-6">
                                                <div class="card-body">
                                                        <h4 class="card-title m-b-0">Dimensions</h4>
                                                </div>
                                                <table class="table">
                                                    <tbody>
                                                        <tr>
                                                            <td>Type</td>
                                                            <td>
                                                                {% if rack.racktype %}
                                                                    {{ rack.get_racktype_display }}
                                                                {% else %}
                                                                    <span class="text-muted">None</span>
                                                                {% endif %}
                                                            </td>
                                                        </tr>

                                                        <tr>
                                                            <td>Height</td>
                                                            <td>{{ rack.u_height }}U ({% if rack.desc_units %}descending{% else %}ascending{% endif %})</td>
                                                        </tr>
                                                  </tbody>
                                                </table>
                                            </div>
                                        </div>


                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="card-body">
                                                    <div>
                                                        <h4 class="card-title m-b-0">Comment</h4>
                                                    </div>
                                                    <div class="alert alert-secondary" role="alert">
                                                      {% if rack.comment %}
                                                            {{ rack.comment }}
                                                        {% else %}
                                                            <span class="text-muted">None</span>
                                                        {% endif %}
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="col-md-6">
                                                <div class="card-body">
                                                    <div>
                                                        <h4 class="card-title m-b-0">Tags</h4>
                                                    </div>
                                                    {% include 'extend/tags_panel.html' with tags=rack.tag.all url='organisation:rack_list' %}
                                                </div>
                                            </div>


                                    </div>
                                </div>

                                <div class="tab-pane active" id="profile" role="tabpanel1">
                                    <div class="p-20">


                                    </div>
                                </div>
                            </div>
                        </div>



{% endblock %}

dc_assistant/templates/organisation/rack_add.html
{% extends "base.html" %}
{% load static %}
{% block content %}

                <div class="row justify-content-center">
                    <div class="col-md-9">
                        <h2 class="card-title">Add new Rack</h2>
                        <div class="card">
                            <form class="form form-horizontal" method="post" id="RackAddForm">
                                <div class="card-body">
                                        {% csrf_token %}
                                        {{ form.as_p }}
                                </div>
                                <div class="border-top">
                                    <div class="card-body">
                                        {% include 'extend/cu_buttons.html' with obj=rack %}
                                        <a href="{% url 'organisation:rack_list' %}" class="btn btn-default">Cancel</a>
                                    </div>
                                </div>
                            </form>

                        </div>
                    </div>
                </div>

{% endblock %}

dc_assistant/templates/organisation/racks_tab.html
{% extends "base.html" %}
{% load static %}
{% load django_tables2 %}

{% block content %}
        <!-- ============================================================== -->
        <!-- Buttons-->
        <!-- ============================================================== -->
         <div class="container-fluid">
            <div class="row justify-content-end">
                <div class="col-md-9 col-sm-9">
                    <h2 class="card-title">Racks</h2>
                </div>
                <div class="col-md-3 col-sm-3 text-right">
                    <a class="btn btn-primary btn-lg" href="{% url 'organisation:rack_add' %}" role="button">Add</a>
                </div>
            </div>
         </div>
         <hr>
        <!-- ============================================================== -->
        <!-- End Buttons-->
        <!-- ============================================================== -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                   <div class="table-responsive">
                       {% render_table table 'organisation/tmpl_table.html' %}
                   </div>
                </div>
            </div>
        </div>
{% endblock %}

dc_assistant/templates/organisation/region_tab.html
{% extends "base.html" %}
{% load static %}
{% load django_tables2 %}

{% block content %}


        <!-- ============================================================== -->
        <!-- Buttons-->
        <!-- ============================================================== -->
         <div class="container-fluid">
            <div class="row justify-content-end">
                <div class="col-md-9 col-sm-9">
                    <h2 class="card-title"> Regions </h2>
                </div>
                <div class="col-md-3 col-sm-3 text-right">
                    <a class="btn btn-primary btn-lg" href="{% url 'organisation:region_add' %}" role="button">Add</a>
                </div>
            </div>
         </div>
         <hr>
        <!-- ============================================================== -->
        <!-- End Buttons-->
        <!-- ============================================================== -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                   <div class="table-responsive">
                       {% render_table table 'organisation/tmpl_table.html' %}
                   </div>
                </div>

            </div>
        </div>
{% endblock %}

dc_assistant/templates/organisation/vendor_add.html
{% extends "base.html" %}
{% load static %}
{% block content %}

                <div class="row justify-content-center">
                    <div class="col-md-9">
                        <h2 class="card-title">Add new Vendor</h2>
                        <div class="card">
                            <form class="form form-horizontal" method="post" id="PlatformAddForm">
                                <div class="card-body">
                                        {% csrf_token %}
                                        {{ form.as_p }}
                                </div>
                                <div class="border-top">
                                    <div class="card-body">
                                        {% include 'extend/cu_buttons.html' with obj=vendor %}
                                        <a href="{% url 'organisation:vendor_list' %}" class="btn btn-default">Cancel</a>
                                    </div>
                                </div>
                            </form>

                        </div>
                    </div>
                </div>

{% endblock %}

dc_assistant/templates/organisation/vendor_tab.html
{% extends "base.html" %}
{% load static %}
{% load django_tables2 %}

{% block content %}
        <!-- ============================================================== -->
        <!-- Buttons-->
        <!-- ============================================================== -->
        <div class="container-fluid">
            <div class="row justify-content-end">
                <div class="col-md-9 col-sm-9">
                    <h2 class="card-title">Vendors</h2>
                </div>
                <div class="col-md-3 col-sm-3 text-right">
                    <a class="btn btn-primary btn-lg" href="{% url 'organisation:vendor_add' %}" role="button">Add</a>
                </div>
            </div>
         </div>
         <hr>
        <!-- ============================================================== -->
        <!-- End Buttons-->
        <!-- ============================================================== -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="table-responsive">
                       {% render_table table 'organisation/tmpl_table.html' %}
                    </div>
                </div>

            </div>
        </div>
{% endblock %}