dc_assistant/dc_assistant/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from .views import MainView, APIRootView
from secret.views import UserLoginView, UserProfileView, UserChangePasswordView
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView
from dc_assistant.admin import admin_site

urlpatterns = [
    path('', MainView.as_view(), name='home'),
    path('admin/', admin_site.urls),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('change-password/', UserChangePasswordView.as_view(), name='change_password'),
    path('change-password/done/', PasswordChangeDoneView.as_view(template_name='secret/change_password_done.html'), name='change_password_done'),
    path('api/', APIRootView.as_view(), name='api-root'),
    path('api/secrets/', include('secret.api.urls')),
    path('api/organisation/', include('organisation.api.urls')),
    path('organisation/', include('organisation.urls')),
    path('extend/', include('extend.urls')),
    path('secret/', include('secret.urls')),
    ]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

dc_assistant/extend/urls.py
from django.urls import path, re_path

from extend import views
from .views import RackAutocomplete


app_name = 'extend'
urlpatterns = [

    path('tags/', views.TagListView.as_view(), name='tag_list'),
    path('rack-autocomplete', RackAutocomplete.as_view(), name='rack_autocomplete'),
    ]

dc_assistant/organisation/urls.py
from django.urls import path
from . import views
from secret.views import secret_add


app_name = 'organisation'

urlpatterns = [
    path('regions/', views.RegionListView.as_view(), name='region_list'),
    path('regions/add', views.RegionAdd.as_view(), name='region_add'),
    path('regions/<int:pk>/edit', views.RegionEdit.as_view(), name='region_edit'),

    path('locations/', views.LocationListView.as_view(), name='location_list'),
    path('locations/add', views.LocationAdd.as_view(), name='location_add'),
    path('locations/<slug:slug>/', views.LocationView.as_view(), name='location'),
    path('locations/<slug:slug>/edit', views.LocationEdit.as_view(), name='location_edit'),

    path('racks/', views.RackListView.as_view(), name='rack_list'),
    path('racks/add', views.RackAdd.as_view(), name='rack_add'),
    path('racks/<int:pk>/', views.RackView.as_view(), name='rack'),
    path('racks/<int:pk>/edit/', views.RackEdit.as_view(), name='rack_edit'),

    path('models/', views.VendorModelListView.as_view(), name='model_list'),
    path('models/add', views.VendorModelAdd.as_view(), name='model_add'),
    path('models/<int:pk>/edit/', views.VendorModelEdit.as_view(), name='model_edit'),

    path('roles/', views.RoleDeviceListView.as_view(), name='role_list'),
    path('roles/add', views.RoleDeviceAdd.as_view(), name='role_add'),
    path('roles/<int:pk>/edit/', views.RoleDeviceEdit.as_view(), name='role_edit'),

    path('platforms/', views.PlatformListView.as_view(), name='platform_list'),
    path('platforms/add', views.PlatformAdd.as_view(), name='platfrom_add'),
    path('platforms/<slug:slug>/edit/', views.PlatformEdit.as_view(), name='platform_edit'),

    path('vendors/', views.VendorListView.as_view(), name='vendor_list'),
    path('vendors/add', views.VendorAdd.as_view(), name='vendor_add'),
    path('vendors/<int:pk>/edit/', views.VendorEdit.as_view(), name='vendor_edit'),

    path('devices/', views.DeviceListView.as_view(), name='device_list'),
    path('devices/add', views.DeviceAdd.as_view(), name='device_add'),
    path('devices/<int:pk>/', views.DeviceView.as_view(), name='device'),
    path('devices/<int:pk>/edit/', views.DeviceEdit.as_view(), name='device_edit'),
    path('devices/<int:pk>/add-secret/', secret_add, name='device_addsecret'),

]

dc_assistant/secret/urls.py
from django.urls import path
from . import views

app_name = 'secret'

urlpatterns = [
    path('user-key/', views.UserKeyView.as_view(), name='userkey'),
    path('user-key/edit/', views.UserKeyAddEditView.as_view(), name='userkey_edit'),
    path('secrets/', views.SecretListView.as_view(), name='secret_list'),
    path('secrets/<int:pk>/', views.SecretView.as_view(), name='secret'),

    path('secret-roles/', views.SecretRoleListView.as_view(), name='secretrole_list'),
    path('secret-roles/add/', views.SecretRoleAdd.as_view(), name='secretrole_add'),
    path('secret-roles/<slug:slug>/edit/', views.SecretRoleEdit.as_view(), name='secretrole_edit'),
    ]

dc_assistant/secret/models.py
import os
from django.db import models
from django.contrib.auth.models import Group, User
from django.core.exceptions import ValidationError

from Crypto.Cipher import AES
from Crypto.PublicKey import RSA
from Crypto.Util import strxor

from django.shortcuts import reverse
from django.utils.encoding import force_bytes
from django.db.models import QuerySet
from .utils import encrypt_master_key, decrypt_master_key, generate_random_key
from django.contrib.auth.hashers import make_password, check_password
from taggit.managers import TaggableManager
from extend.models import TaggedItem, LoggingModel
from organisation.models import Device
from django.contrib.auth.hashers import PBKDF2PasswordHasher


__all__ = (
    'Secret',
    'SecretRole',
    'SessionKey',
    'UserKey',
)

class InvalidKey(Exception):
    """
    When a provided key is invalid.
    """
    pass


class SecretValidationHasher(PBKDF2PasswordHasher):
    """
    Django integrated SHA256 hasher with a low iteration count to avoid delay
    """
    iterations = 1000


class UserKeyQuerySet(QuerySet):

    def active(self):
        return self.filter(master_key_cipher__isnull=False)


class UserKey(models.Model):
    """
    A UserKey actualy is a user's personal key (public key). Personal key is used to make a master encryption key.
    The encrypted secrets (device passwords as secrets in model secrets an so on) of the master key can be decrypted only with the user's
    matching private key. Private key user have to save(copy to file, notes) private key as do their other
    private keys (for example private key for access to servers by ssh)
    """
    created = models.DateField(
        auto_now_add=True
    )
    last_updated = models.DateTimeField(
        auto_now=True
    )
    user = models.OneToOneField(
        to=User,
        on_delete=models.CASCADE,
        related_name='user_key',
        editable=False
    )
    public_key = models.TextField(
        verbose_name='RSA public key'
    )
    master_key_cipher = models.BinaryField(
        max_length=512,
        blank=True,
        null=True,
        editable=False
    )
    objects = UserKeyQuerySet.as_manager()

    class Meta:
        ordering = ['user__username']
        # permissions = (
        #     ('activate_userkey', "Can activate user keys for decryption"),
        # )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Store the initial public_key and master_key_cipher to check for changes on save().
        self.__initial_public_key = self.public_key
        self.__initial_master_key_cipher = self.master_key_cipher

    def __str__(self):
        return self.user.username

    def clean(self, *args, **kwargs):

        if self.public_key:
            # Validate the public key format
            try:
                pubkey = RSA.import_key(self.public_key)
            except ValueError:
                raise ValidationError({
                    'public_key': "Invalid RSA key format."
                })
            except Exception:
                raise ValidationError("Something wrong trying to save your key. Please ensure that you're "
                                      "uploading a valid public key in PEM format (no SSH or PGP).")
            # Validate the public key length
            pubkey_length = pubkey.size_in_bits()
            if pubkey_length < 2048:
                raise ValidationError({
                    'public_key': "Insufficient key length. Keys must be at least {} bits long.".format(2048)
                })
            # Can't use keys bigger than our master_key_cipher field can hold
            if pubkey_length > 4096:
                raise ValidationError({
                    'public_key': "Public key size ({}) is too large. Maximum key size is 4096 bits.".format(pubkey_length)
                })

        super().clean()

    def save(self, *args, **kwargs):
        # Check that public_key was modified. If yes, clean the initial master_key_cipher.
        if self.__initial_master_key_cipher and self.public_key != self.__initial_public_key:
            self.master_key_cipher = None
        # If no other active UserKeys exist, generate a new master key and use it to activate this UserKey.
        if self.is_filled() and not self.is_active() and not UserKey.objects.active().count():
            master_key = generate_random_key()
            self.master_key_cipher = encrypt_master_key(master_key, self.public_key)

        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        # If Secrets exist and this is the last active UserKey, prevent its deletion. Deleting the last UserKey will
        # result in the master key being destroyed and rendering all Secrets inaccessible.
        if Secret.objects.count() and [uk.pk for uk in UserKey.objects.active()] == [self.pk]:
            raise Exception("!!!Cannot delete the last active UserKey when Secrets exist!!!")

        super().delete(*args, **kwargs)

    def is_filled(self):
        """
        trick: returns True if the UserKey is filled with a public key.
        """
        return bool(self.public_key)
    is_filled.boolean = True

    def is_active(self):
        """
        trick: returns True if the UserKey is populated with an encrypted copy of the master key.
        """
        return self.master_key_cipher is not None
    is_active.boolean = True

    def get_master_key(self, private_key):
        """
        Return the encrypted master key when user gives private key,
        """
        if not self.is_active:
            raise ValueError("Unable to retrieve master key: UserKey is inactive.")
        try:
            return decrypt_master_key(force_bytes(self.master_key_cipher), private_key)
        except ValueError:
            return None

    def activate(self, master_key):
        """
        Activate the UserKey by saving encrypted copy of the master key.
        """
        if not self.public_key:
            raise Exception("Cannot activate UserKey: Public key must be filled first.")
        self.master_key_cipher = encrypt_master_key(master_key, self.public_key)
        self.save()


class SecretRole(LoggingModel):
    """
    A SecretRole is functional classification of Secrets.
    By default, only superusers will have access to decrypt all Secrets.
    To allow other users to decrypt Secrets, grant them permissions by adding to the same group as SecretRoles.
    """
    name = models.CharField(
        max_length=50,
        unique=True
    )
    slug = models.SlugField(
        unique=True
    )
    description = models.CharField(
        max_length=100,
        blank=True,
    )
    users = models.ManyToManyField(
        to=User,
        related_name='secretroles',
        blank=True
    )
    groups = models.ManyToManyField(
        to=Group,
        related_name='secretroles',
        blank=True
    )

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return "{}?role={}".format(reverse('secret:secret_list'), self.slug)

    def has_member(self, user):
        """
        Check that user(group) belongs to this SecretRole. Superusers belong to all roles.
        """
        if user.is_superuser:
            return True
        return user in self.users.all() or user.groups.filter(pk__in=self.groups.all()).exists()


class SessionKey(models.Model):
    """
    A SessionKey is User's temporary key for the encryption and decryption of secrets.
    """
    userkey = models.OneToOneField(
        to=UserKey,
        on_delete=models.CASCADE,
        related_name='session_key',
        editable=False
    )
    cipher = models.BinaryField(
        max_length=512,
        editable=False
    )
    hash = models.CharField(
        max_length=128,
        editable=False
    )
    created = models.DateTimeField(
        auto_now_add=True
    )

    key = None

    class Meta:
        ordering = ['userkey__user__username']

    def __str__(self):
        return self.userkey.user.username

    def save(self, master_key=None, *args, **kwargs):

        if master_key is None:
            raise Exception("The master key needs to save a session key.")

        # Generate random 256-bit session key if no one defined
        if self.key is None:
            self.key = generate_random_key()
        # Generate SHA256 hash using Django's built-in password hashing mechanism
        self.hash = make_password(self.key)
        # Encrypt master key using the session key
        self.cipher = strxor.strxor(self.key, master_key)

        super().save(*args, **kwargs)

    def get_master_key(self, session_key):

        # Validate the provided session key
        if not check_password(session_key, self.hash):
            raise InvalidKey("Invalid session key")
        # Decrypt master key using provided session key
        master_key = strxor.strxor(session_key, bytes(self.cipher))

        return master_key

    def get_session_key(self, master_key):
        print(master_key)

        # Recover session key using the master key
        session_key = strxor.strxor(master_key, bytes(self.cipher))
        # Validate the recovered session key
        if not check_password(session_key, self.hash):
            raise InvalidKey("Invalid master key")

        return session_key


class Secret(LoggingModel):
    """
    A Secret is AES256-encrypted instance of sensitive data, such as passwords or secret keys. Irreversible
    SHA-256 hash is stored with the ciphertext for validation when need to decrypt.
    Each Secret is assigned to Device. Devices may have a lot of Secrets.
    A name (It my be login in case if secret is login/password pair) stored as plain text in the database.
    A Secret can be up to 65535 bytes (64KB) in length.
    Each secret string is padded with random data to a minimum of 64 bytes during encryption to protect short strings.
    """

dc_assistant/templates/home.html
{% extends "base.html" %}
{% load static %}
{% load django_tables2 %}
{% load utils %}

{% block content %}
                <div class="row">
                    <!-- ============================================================== -->
                    <!-- Left column main page -->
                    <!-- ============================================================== -->
                    <div class="col-md-4 col-lg-4 col-xlg-4">

                        <div class="card card-hover">
                            <div class="box bg-success text-left ">
                                <h1 class="font-light text-white"><i class="mdi mdi-view-dashboard"></i></h1>
                                <h2 class="text-white">Organisation</h2>
                                <table class="table text-white">
                                    <tbody>
                                    <tr>
                                        <td><h4>Regions</h4></td>
                                        <td>
                                            {% if perms.organisation.view_region %}
                                                <h4 class="list-group-item-heading"><a href="{% url 'organisation:region_list' %}" style="color: white">{{ stats.region_count }}</a></h4>
                                            {% else %}
                                                <span class="badge pull-right"><i class="fas fa-lock"></i></span>
                                            {% endif %}
                                        </td>
                                    </tr>
                                    <tr>
                                        <td><h4>Locations</h4></td>
                                        <td>
                                            {% if perms.organisation.view_region %}
                                            <h4 class="list-group-item-heading"><a href="{% url 'organisation:location_list' %}" style="color: white">{{ stats.location_count }}</a></h4>
                                            {% else %}
                                                <span class="badge pull-right"><i class="fas fa-lock"></i></span>
                                            {% endif %}
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>

                        <div class="card card-hover">
                            <div class="box bg-cyan text-left ">
                                <h1 class="font-light text-white"><i class="mdi mdi-server"></i></h1>
                                <h2 class="text-white">Phisical Devices</h2>
                                <table class="table text-white">
                                    <tbody>
                                    <tr>
                                        <td><h4>Racks</h4></td>
                                        <td>
                                            {% if perms.organisation.view_rack %}
                                                <h4 class="list-group-item-heading"><a href="{% url 'organisation:rack_list' %}" style="color: white">{{ stats.rack_count }}</a></h4>
                                            {% else %}
                                                <span class="badge pull-right"><i class="fas fa-lock"></i></span>
                                            {% endif %}
                                        </td>
                                    </tr>
                                    <tr>
                                        <td><h4>Device Models</h4></td>
                                        <td>
                                            {% if perms.organisation.view_vendormodel %}
                                                <h4 class="list-group-item-heading"><a href="{% url 'organisation:model_list' %}" style="color: white">{{ stats.devicemodel_count }}</a></h4>
                                            {% else %}
                                                <span class="badge pull-right"><i class="fas fa-lock"></i></span>
                                            {% endif %}
                                        </td>
                                    </tr>
                                    <tr>
                                        <td><h4>Devices</h4></td>
                                        <td>
                                            {% if perms.organisation.view_device %}
                                                <h4 class="list-group-item-heading"><a href="{% url 'organisation:device_list' %}" style="color: white">{{ stats.device_count }}</a></h4>
                                            {% else %}
                                                <span class="badge pull-right"><i class="fas fa-lock"></i></span>
                                            {% endif %}
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>

                    </div>
                    <!-- ============================================================== -->
                    <!-- Center column main page -->
                    <!-- ============================================================== -->
                    <div class="col-md-4 col-lg-4 col-xlg-4">

                        <div class="card card-hover">
                            <div class="box bg-info text-left ">
                                <h1 class="font-light text-white"><i class="mdi mdi-cloud"></i></h1>
                                <h2 class="text-white">Virtualisation</h2>
                                <table class="table text-white">
                                    <tbody>
                                    <tr>
                                        <td><h4>VMs</h4></td>
                                        <td>
                                            <h4 class="list-group-item-heading"><a href="#" style="color: white">in developing</a></h4>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td><h4>Virtual Clusters</h4></td>
                                        <td>
                                            <h4 class="list-group-item-heading"><a href="#" style="color: white">in developing</a></h4>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>

                        <div class="card card-hover">
                            <div class="box bg-warning text-left ">
                                <h1 class="font-light text-white"><i class="mdi mdi-network"></i></h1>
                                <h2 class="text-white">Networking</h2>
                                <table class="table text-white">
                                    <tbody>
                                    <tr>
                                        <td><h4>IP Addresses</h4></td>
                                        <td>
                                            <h4 class="list-group-item-heading"><a href="#" style="color: white">in developing</a></h4>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td><h4>VLAN/Subnets</h4></td>
                                        <td>
                                            <h4 class="list-group-item-heading"><a href="#" style="color: white">in developing</a></h4>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>

                    </div>
                    <!-- ============================================================== -->
                    <!-- Right column main page -->
                    <!-- ============================================================== -->
                    <div class="col-md-4 col-lg-4 col-xlg-4">

                        <div class="card card-hover">
                            <div class="box bg-danger text-left ">
                                <h1 class="font-light text-white"><i class="mdi mdi-lock"></i></h1>
                                <h2 class="text-white">Secrets</h2>
                                <table class="table text-white">
                                    <tbody>

                                    <tr>
                                        <td><h4>Secrets</h4></td>
                                        <td>
                                            {% if perms.secret.view_secret %}
                                            <h4 class="list-group-item-heading"><a href="{% url 'secret:secret_list' %}" style="color: white">{{ stats.secret_count }}</a></h4>
                                            {% else %}
                                                <span class="badge pull-right"><i class="fas fa-lock"></i></span>
                                            {% endif %}
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>

                    </div>

                </div>


{% endblock %}