dc_assistant/dc_assistant/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from .views import MainView, APIRootView
from secret.views import UserLoginView, UserProfileView, UserChangePasswordView
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView
from dc_assistant.admin import admin_site

urlpatterns = [
    path('', MainView.as_view(), name='home'),
    path('admin/', admin_site.urls),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('change-password/', UserChangePasswordView.as_view(), name='change_password'),
    path('change-password/done/', PasswordChangeDoneView.as_view(template_name='secret/change_password_done.html'), name='change_password_done'),
    path('api/', APIRootView.as_view(), name='api-root'),
    path('api/secrets/', include('secret.api.urls')),
    path('api/organisation/', include('organisation.api.urls')),
    path('organisation/', include('organisation.urls')),
    path('extend/', include('extend.urls')),
    path('secret/', include('secret.urls')),
    ]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

dc_assistant/extend/urls.py
from django.urls import path, re_path

from extend import views
from .views import RackAutocomplete


app_name = 'extend'
urlpatterns = [

    path('tags/', views.TagListView.as_view(), name='tag_list'),
    path('rack-autocomplete', RackAutocomplete.as_view(), name='rack_autocomplete'),
    ]

dc_assistant/organisation/urls.py
from django.urls import path
from . import views
from secret.views import secret_add


app_name = 'organisation'

urlpatterns = [
    path('regions/', views.RegionListView.as_view(), name='region_list'),
    path('regions/add', views.RegionAdd.as_view(), name='region_add'),
    path('regions/<int:pk>/edit', views.RegionEdit.as_view(), name='region_edit'),

    path('locations/', views.LocationListView.as_view(), name='location_list'),
    path('locations/add', views.LocationAdd.as_view(), name='location_add'),
    path('locations/<slug:slug>/', views.LocationView.as_view(), name='location'),
    path('locations/<slug:slug>/edit', views.LocationEdit.as_view(), name='location_edit'),

    path('racks/', views.RackListView.as_view(), name='rack_list'),
    path('racks/add', views.RackAdd.as_view(), name='rack_add'),
    path('racks/<int:pk>/', views.RackView.as_view(), name='rack'),
    path('racks/<int:pk>/edit/', views.RackEdit.as_view(), name='rack_edit'),

    path('models/', views.VendorModelListView.as_view(), name='model_list'),
    path('models/add', views.VendorModelAdd.as_view(), name='model_add'),
    path('models/<int:pk>/edit/', views.VendorModelEdit.as_view(), name='model_edit'),

    path('roles/', views.RoleDeviceListView.as_view(), name='role_list'),
    path('roles/add', views.RoleDeviceAdd.as_view(), name='role_add'),
    path('roles/<int:pk>/edit/', views.RoleDeviceEdit.as_view(), name='role_edit'),

    path('platforms/', views.PlatformListView.as_view(), name='platform_list'),
    path('platforms/add', views.PlatformAdd.as_view(), name='platfrom_add'),
    path('platforms/<slug:slug>/edit/', views.PlatformEdit.as_view(), name='platform_edit'),

    path('vendors/', views.VendorListView.as_view(), name='vendor_list'),
    path('vendors/add', views.VendorAdd.as_view(), name='vendor_add'),
    path('vendors/<int:pk>/edit/', views.VendorEdit.as_view(), name='vendor_edit'),

    path('devices/', views.DeviceListView.as_view(), name='device_list'),
    path('devices/add', views.DeviceAdd.as_view(), name='device_add'),
    path('devices/<int:pk>/', views.DeviceView.as_view(), name='device'),
    path('devices/<int:pk>/edit/', views.DeviceEdit.as_view(), name='device_edit'),
    path('devices/<int:pk>/add-secret/', secret_add, name='device_addsecret'),

]

dc_assistant/secret/api/urls.py
from rest_framework import routers
from .views import SecretsRootView, GenerateRSAKeyPairViewSet, GetSessionKeyViewSet, SecretViewSet


router = routers.DefaultRouter()
router.APIRootView = SecretsRootView

router.register('get-session-key', GetSessionKeyViewSet, basename='get-session-key')
router.register('generate-rsa-key-pair', GenerateRSAKeyPairViewSet, basename='generate-rsa-key-pair')
router.register('secrets', SecretViewSet)

app_name = 'secrets-api'
urlpatterns = router.urls

dc_assistant/secret/urls.py
from django.urls import path
from . import views

app_name = 'secret'

urlpatterns = [
    path('user-key/', views.UserKeyView.as_view(), name='userkey'),
    path('user-key/edit/', views.UserKeyAddEditView.as_view(), name='userkey_edit'),
    path('secrets/', views.SecretListView.as_view(), name='secret_list'),
    path('secrets/<int:pk>/', views.SecretView.as_view(), name='secret'),

    path('secret-roles/', views.SecretRoleListView.as_view(), name='secretrole_list'),
    path('secret-roles/add/', views.SecretRoleAdd.as_view(), name='secretrole_add'),
    path('secret-roles/<slug:slug>/edit/', views.SecretRoleEdit.as_view(), name='secretrole_edit'),
    ]

dc_assistant/secret/api/views.py
import base64
from rest_framework import routers
from rest_framework.viewsets import ViewSet, ModelViewSet
from rest_framework.permissions import IsAuthenticated
from rest_framework.exceptions import ValidationError
from Crypto.PublicKey import RSA
from rest_framework.response import Response
from django.http import HttpResponseBadRequest
from secret.models import UserKey, SessionKey, Secret
from extend.filters import SecretFilterSet
from .serializers import SecretSerializer

ERR_USERKEY_MISSING = "No UserKey found for the current user."
ERR_USERKEY_INACTIVE = "UserKey has not been activated for decryption."
ERR_PRIVKEY_MISSING = "Private key was not provided."
ERR_PRIVKEY_INVALID = "Invalid private key."

class InvalidKey(Exception):
    """
    Raised when a provided key is invalid.
    """
    pass

class SecretsRootView(routers.APIRootView):
    """
    Secrets API root view
    """
    def get_view_name(self):
        return 'Secrets'


class GenerateRSAKeyPairViewSet(ViewSet):
    """
    Generate a new RSA key pair. The keys are returned in PEM format.
        {
            "public_key": "<public key>",
            "private_key": "<private key>"
        }
    """
    permission_classes = [IsAuthenticated]

    def list(self, request):

        # Determine what size key to generate
        key_size = request.GET.get('key_size', 2048)
        if key_size not in range(2048, 4097, 256):
            key_size = 2048

        # Export RSA private and public keys in PEM format
        key = RSA.generate(key_size)
        private_key = key.exportKey('PEM')
        public_key = key.publickey().exportKey('PEM')

        return Response({
            'private_key': private_key,
            'public_key': public_key,
        })

class GetSessionKeyViewSet(ViewSet):
    """
    Retrieve a temporary session key to use for encrypting and decrypting secrets via the API. The user's private RSA
    key is POSTed with the name `private_key`.
    For example:

        curl -v -X POST -H "Authorization: Token <token>" -H "Accept: application/json; indent=4" \\
        --data-urlencode "private_key@<filename>" https://dcassistant/api/secrets/get-session-key/

    This request will yield a base64-encoded session key to be included in an `X-Session-Key` header in future requests:

        {
            "session_key": "+8t4SI6XikgVmB5+/urhozx9O5qCQANyOk1MNe6taRf="
        }

    This endpoint accepts one optional parameter: `preserve_key`. If True and a session key exists, the existing session
    key will be returned instead of a new one.
    """
    permission_classes = [IsAuthenticated]

    def create(self, request):

        # Read private key
        private_key = request.POST.get('private_key', None)
        if private_key is None:
            return HttpResponseBadRequest(ERR_PRIVKEY_MISSING)

        # Validate user key
        try:
            user_key = UserKey.objects.get(user=request.user)
        except UserKey.DoesNotExist:
            return HttpResponseBadRequest(ERR_USERKEY_MISSING)
        if not user_key.is_active():
            return HttpResponseBadRequest(ERR_USERKEY_INACTIVE)

        # Validate private key
        master_key = user_key.get_master_key(private_key)
        if master_key is None:
            return HttpResponseBadRequest(ERR_PRIVKEY_INVALID)

        try:
            current_session_key = SessionKey.objects.get(userkey__user_id=request.user.pk)
        except SessionKey.DoesNotExist:
            current_session_key = None

        if current_session_key and request.GET.get('preserve_key', False):

            # Retrieve the existing session key
            key = current_session_key.get_session_key(master_key)

        else:

            # Create a new SessionKey
            SessionKey.objects.filter(userkey__user=request.user).delete()
            sk = SessionKey(userkey=user_key)
            sk.save(master_key=master_key)
            key = sk.key

        # Encode the key using base64. (b64decode() returns a bytestring under Python 3.)
        encoded_key = base64.b64encode(key).decode()

        # Craft the response
        response = Response({
            'session_key': encoded_key,
        })

        # If token authentication is not in use, assign the session key as a cookie
        if request.auth is None:
            response.set_cookie('session_key', value=encoded_key)

        return response


class SecretViewSet(ModelViewSet):
    queryset = Secret.objects.prefetch_related(
        'role', 'role__users', 'role__groups',
    )
    serializer_class = SecretSerializer
    filterset_class = SecretFilterSet

    master_key = None

    def get_serializer_context(self):

        # Make the master key available to the serializer for encrypting plaintext values
        context = super().get_serializer_context()
        context['master_key'] = self.master_key

        return context

    def initial(self, request, *args, **kwargs):

        super().initial(request, *args, **kwargs)

        if request.user.is_authenticated:

            # read session key from HTTP cookie or header. The session key must exist in order to encrypt/decrypt.
            if 'session_key' in request.COOKIES:
                session_key = base64.b64decode(request.COOKIES['session_key'])
            elif 'HTTP_X_SESSION_KEY' in request.META:
                session_key = base64.b64decode(request.META['HTTP_X_SESSION_KEY'])
            else:
                session_key = None

            # can't encrypt secret plaintext without a session key.
            if self.action in ['create', 'update'] and session_key is None:
                raise ValidationError("A session key must exist when creatt or update secrets.")

            # get master key for encryption/decryption if a session key exist.
            if session_key is not None:
                try:
                    sk = SessionKey.objects.get(userkey__user=request.user)
                    self.master_key = sk.get_master_key(session_key)
                except (SessionKey.DoesNotExist, InvalidKey):
                    raise ValidationError("Invalid session key.")

    def retrieve(self, request, *args, **kwargs):

        secret = self.get_object()

        # decrypt the secret if the user have permission and the master key exist
        if secret.decryptable_by(request.user) and self.master_key is not None:
            secret.decrypt(self.master_key)

        serializer = self.get_serializer(secret)
        return Response(serializer.data)

    def list(self, request, *args, **kwargs):

        queryset = self.filter_queryset(self.get_queryset())

        page = self.paginate_queryset(queryset)
        if page is not None:

            # decrypt all secrets if the master key exist
            if self.master_key is not None:
                secrets = []
                for secret in page:
                    # Enforce role permissions
                    if secret.decryptable_by(request.user):
                        secret.decrypt(self.master_key)
                    secrets.append(secret)
                serializer = self.get_serializer(secrets, many=True)
            else:
                serializer = self.get_serializer(page, many=True)

            return self.get_paginated_response(serializer.data)

        serializer = self.get_serializer(queryset, many=True)
        return Response(serializer.data)

dc_assistant/templates/secret/activate_keys.html
{% extends "admin/base_site.html" %}

{% block content %}

<form action="." method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="hidden" name="action" value="activate_selected" />
    <input type="submit" name="activate" value="Activate User Key(s)" />
</form>

{% endblock %}

dc_assistant/templates/secret/change_password_done.html
{% extends "secret/usermenu.html" %}
{% load static %}

{% block usercontent %}

<div class="card-body border-top">
    <h5 class="card-title">Password change</h5>
    <div class="alert alert-success" role="alert">
      <h4 class="alert-heading">Well done!</h4>
      <p>Your password has been successfully changed</p>
    </div>
</div>

{% endblock %}

dc_assistant/templates/secret/profile.html
{% extends "secret/usermenu.html" %}
{% load static %}

{% block title %}User Profile{% endblock %}

{% block usercontent %}
    <small class="text-muted">User login</small>
    <h5>{{ request.user.username }}</h5>
    <small class="text-muted">Full name</small>
    <h5>{{ request.user.first_name }} {{ request.user.last_name }}</h5>
    <small class="text-muted">Email</small>
    <h5>{{ request.user.email }}</h5>
    <small class="text-muted">Registered</small>
    <h5>{{ request.user.date_joined }}</h5>
    <small class="text-muted">Groups</small>
    <h5>{{ request.user.groups.all|join:', ' }}</h5>
    <small class="text-muted">Admin access</small>
    <h5>{{ request.user.is_staff|yesno|capfirst }}</h5>
{% endblock %}

dc_assistant/templates/secret/secret.html
{% extends 'base.html' %}
{% load static %}
{% load utils %}

{% block content %}
<div class="row">
	<div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <strong>Secret Attributes</strong>
            </div>
            <table class="table table-hover panel-body">
                <tr>
                    <td>Device</td>
                    <td>
                        <a href="{% url 'organisation:device' pk=secret.device.pk %}">{{ secret.device }}</a>
                    </td>
                </tr>
                <tr>
                    <td>Role</td>
                    <td>{{ secret.role }}</td>
                </tr>
                <tr>
                    <td>Name</td>
                    <td>{{ secret.name }}</td>
                </tr>
            </table>
        </div>
	</div>
	<div class="col-md-6">
        {% if secret|decryptable_by:request.user %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <strong>Secret Data</strong>
                </div>
                <div class="panel-body">
                    <form id="secret_form">
                        {% csrf_token %}
                    </form>
                    <div class="row">
                        <div class="col-md-2">Secret</div>
                        <div class="col-md-6" id="secret_{{ secret.pk }}">********</div>
                        <div class="col-md-4 text-right noprint">
                            <button class="btn btn-xs btn-success unlock-secret" secret-id="{{ secret.pk }}">
                                <i class="fas fa-lock"></i> Unlock
                            </button>
                            <button class="btn btn-xs btn-default copy-secret collapse" secret-id="{{ secret.pk }}" data-clipboard-target="#secret_{{ secret.pk }}">
                                <i class="fas fa-copy"></i> Copy
                            </button>
                            <button class="btn btn-xs btn-danger lock-secret collapse" secret-id="{{ secret.pk }}">
                                <i class="fas fa-unlock-alt"></i> Lock
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        {% else %}
            <div class="alert alert-warning">
                <i class="fa fa-warning" aria-hidden="true"></i>
                You do not have permission to decrypt this secret.
            </div>
        {% endif %}
    </div>
</div>

<div class="modal fade none-border" id="privkey_modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-md" role="document">
        <div class="modal-content">

            <div class="modal-header">
                <h4 class="modal-title" id="privkey_modal_title"><span class="fas fa-lock" aria-hidden="true"></span><strong> Enter your private RSA key</strong></h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>

            <div class="modal-body">
                <p>There is no active session key. To request it, paste your private key. Your session key will be saved for future requests at this session.</p>
                <div class="form-group">
                    <textarea class="form-control" id="user_privkey" style="height: 300px;"></textarea>
                </div>
                <div class="form-group text-right noprint">
                    <button id="request_session_key" class="btn btn-primary" data-dismiss="modal">Request session key</button>
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock %}

{% block pagescript %}
<script src="{% static 'dist/js/secrets.js' %}"></script>
{% endblock %}

dc_assistant/templates/secret/secret_add_edit.html
{% extends 'base.html' %}
{% load static %}
{% load utils %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-md-9">

        <h2>{% block title %}{% if secret.pk %}Edit Secret {{ secret }}{% else %}Add Secret{% endif %}{% endblock %}</h2>
        <div class="card">
            <form action="." method="post" class="form form-horizontal">
                {% csrf_token %}
                {% for field in form.hidden_fields %}
                    {{ field }}
                {% endfor %}
                {% if form.non_field_errors %}
                    <div class="card-body">
                        <h5 class="card-title" style="color: white">Errors</h5>
                        <div class="alert alert-danger" role="alert">
                          {{ form.non_field_errors }}
                        </div>
                    </div>
                {% endif %}
                {{ form.private_key }}
                <div class="row">
                        <div class="card-body">
                            <div class="panel-body">
                                <p>
                                <label class="col-md-3 control-label required"><strong>Device</strong></label>
                                {{ secret.device }}
                                </p>
                                <p>
                                {{ form.name.errors }}
                                <label class="col-md-3 control-label" for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
                                {{ form.name }}
                                </p>
                                <p>
                                {{ form.role.errors }}
                                <label class="col-md-3 control-label" for="{{ form.role.id_for_label }}">{{ form.role.label }}</label>
                                {{ form.role }}
                                </p>
                                {{ form.userkeys }}
                            </div>

                                {% if secret.pk and secret|decryptable_by:request.user %}
                                    <div class="form-group">
                                        <label class="col-md-3 control-label required">Current Plaintext</label>
                                        <div class="col-md-7">
                                            <p class="form-control-static" id="secret_{{ secret.pk }}">********</p>
                                        </div>
                                        <div class="col-md-2 text-right">
                                            <button class="btn btn-xs btn-success unlock-secret" secret-id="{{ secret.pk }}">
                                                <i class="fa fa-lock"></i> Unlock
                                            </button>
                                            <button class="btn btn-xs btn-danger lock-secret collapse" secret-id="{{ secret.pk }}">
                                                <i class="fa fa-unlock-alt"></i> Lock
                                            </button>
                                        </div>
                                    </div>
                                {% endif %}

                            <p>
                            {{ form.plaintext.errors }}
                            <label class="col-md-3 control-label" for="{{ form.plaintext.id_for_label }}">{{ form.plaintext.label }}</label>
                            {{ form.plaintext }}
                            </p>

                            <p>
                            {{ form.plaintext2.errors }}
                            <label class="col-md-3 control-label" for="{{ form.plaintext2.id_for_label }}">{{ form.plaintext2.label }}</label>
                            {{ form.plaintext2 }}
                            </p>


                            <div class="panel panel-default">
                                <div class="panel-heading">Tags</div>
                                <div class="panel-body">
                                    {{ form.tag }} <span class="helptext">Вводить через запятую</span>
                                </div>
                            </div>
                        </div>
                </div>
                <div class="row">
                    <div class="card-body">
                        <div class="form-group">
                            <div class="col-md-12 text-left">
                                {% if secret.pk %}
                                    <button type="submit" name="_update" class="btn btn-primary">Update</button>
                                    <a href="{% url 'secret:secret' pk=secret.pk %}" class="btn btn-default">Cancel</a>
                                {% else %}
                                    <button type="submit" name="_create" class="btn btn-primary">Create</button>
                                    <a href="{{ return_url }}" class="btn btn-default">Cancel</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="modal fade none-border" id="privkey_modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-md" role="document">
        <div class="modal-content">

            <div class="modal-header">
                <h4 class="modal-title" id="privkey_modal_title"><span class="fas fa-lock" aria-hidden="true"></span><strong> Enter your private RSA key</strong></h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>

            <div class="modal-body">
                <p>There is no active session key. To request it, paste your private key. Your session key will be saved for future requests at this session.</p>
                <div class="form-group">
                    <textarea class="form-control" id="user_privkey" style="height: 300px;"></textarea>
                </div>
                <div class="form-group text-right noprint">
                    <button id="request_session_key" class="btn btn-primary" data-dismiss="modal">Request session key</button>
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock %}

{% block pagescript %}
<script src="{% static 'dist/js/secrets.js' %}"></script>
{% endblock %}

dc_assistant/templates/secret/secretrole_add.html
{% extends "base.html" %}
{% load static %}
{% block content %}

                <div class="row justify-content-center">
                    <div class="col-md-9">
                        <h2 class="card-title">Add new Secret Role</h2>
                        <div class="card">

                                        <form class="form form-horizontal" method="post" id="DeviceAddForm">
                                            <div class="card-body">
                                                {% csrf_token %}
                                                {{ form.as_p }}
                                            </div>
                                            <div class="border-top">
                                                <div class="card-body">
                                                    {% include 'extend/cu_buttons.html' with obj=secretrole %}
                                                    <a href="{% url 'secret:secretrole_list' %}" class="btn btn-default">Cancel</a>
                                                </div>
                                            </div>
                                        </form>

                        </div>
                    </div>
                </div>

{% endblock %}

{% block pagescript %}
<script>
        //***********************************//
        // For select 2
        //***********************************//
        $(".select2").select2();

        /*colorpicker*/
        $('.demo').each(function() {
        //
        // Dear reader, it's actually very easy to initialize MiniColors. For example:
        //
        //  $(selector).minicolors();
        //
        // The way I've done it below is just for the demo, so don't get confused
        // by it. Also, data- attributes aren't supported at this time...they're
        // only used for this demo.
        //
        $(this).minicolors({
                control: $(this).attr('data-control') || 'hue',
                position: $(this).attr('data-position') || 'bottom left',

                change: function(value, opacity) {
                    if (!value) return;
                    if (opacity) value += ', ' + opacity;
                    if (typeof console === 'object') {
                        console.log(value);
                    }
                },
                theme: 'bootstrap'
            });

        });
        /*datwpicker*/
        jQuery('.mydatepicker').datepicker();
        jQuery('#datepicker-autoclose').datepicker({
            autoclose: true,
            todayHighlight: true
        });
        var quill = new Quill('#editor', {
            theme: 'snow'
        });

    </script>
{% endblock %}

dc_assistant/templates/secret/secretroles_tab.html
{% extends "base.html" %}
{% load static %}
{% load django_tables2 %}
{% load utils %}

{% block content %}
        <!-- ============================================================== -->
        <!-- Buttons-->
        <!-- ============================================================== -->
        <div class="container-fluid">
            <div class="row justify-content-end">
                <div class="col-md-9 col-sm-9">
                    <h2 class="card-title">Secret Roles</h2>
                </div>
                <div class="col-md-3 col-sm-3 text-right">
                    <a class="btn btn-primary btn-lg" href="{% url 'secret:secretrole_add' %}" role="button">Add</a>
                </div>
            </div>
         </div>
         <hr>
        <!-- ============================================================== -->
        <!-- End Buttons-->
        <!-- ============================================================== -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                   <div class="table-responsive">
                       {% render_table table 'organisation/tmpl_table.html' %}
                   </div>
                </div>

            </div>
        </div>
{% endblock %}

dc_assistant/templates/secret/userkey.html
{% extends "secret/usermenu.html" %}
{% load static %}

{% block title %}User Key{% endblock %}

{% block usercontent %}
    {% if userkey %}
        <div class="pull-right noprint">
            <a href="{% url 'secret:userkey_edit' %}" class="btn btn-warning btn-sm">
                <span class="fas fa-edit" aria-hidden="true"></span>
                Edit user key
            </a>
        </div>
        <h4>
            Your user key is:
            {% if userkey.is_active %}
                <span class="badge badge-pill badge-success">Active</span>
            {% else %}
                <span class="badge badge-pill badge-danger">Inactive</span>
            {% endif %}
        </h4>
        {% if not userkey.is_active %}
            <div class="alert alert-warning" role="alert">
                <i class="fas fa-ban"></i>
                Your user key is inactive. Ask an administrator to enable it for you.
            </div>
        {% endif %}
        <div class="card-body">
        <pre>{{ userkey.public_key }}</pre>
        </div>

        <hr />
        {% if userkey.session_key %}
            <h4>Session key is exist: <span class="badge badge-pill badge-success">Active</span></h4>
            <small class="text-muted">Created {{ userkey.session_key.created }}</small>
        {% else %}
            <h4>No active session key</h4>
        {% endif %}
    {% else %}
        <p>You don't have a user key on file.</p>
        <p>
            <a href="{% url 'secret:userkey_edit' %}" class="btn btn-primary">
                <span class="fas fa-plus" aria-hidden="true"></span>
                Create a User Key
            </a>
        </p>
    {% endif %}
{% endblock %}

dc_assistant/templates/secret/usermenu.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="row ">
    <div class="col-sm-12 col-md-8 col-md-offset-2">
        <h1>{% block title %}{% endblock %}</h1>
    </div>
</div>
<hr>
<div class="row ">

    <div class="col-sm-4 col-md-3">
    <div style="background:gray">
        <nav class="sidebar-nav">
            <ul id="sidebarnav" class="p-t-10">
                <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'profile' %}" aria-expanded="false"><i class="mdi mdi-view-dashboard"></i><span class="hide-menu">User Profile </span></a></li>
                <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'change_password' %}" aria-expanded="false"><i class="mdi mdi-chart-bar"></i><span class="hide-menu">Change Password</span></a></li>
                <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'secret:userkey' %}" aria-expanded="false"><i class="mdi mdi-chart-bar"></i><span class="hide-menu">User Keys</span></a></li>
            </ul>
        </nav>
    </div>
    </div>

	<div class="col-sm-8 col-md-6">
        {% block usercontent %}{% endblock %}
	</div>
</div>
{% endblock %}